version: 2.1

# Define the jobs we want to run for this projectttttttttttt
jobs:
  build-second:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job in the second config"
  test-second:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job in the second config"

# Orchestrate our job run sequence
workflows:
  build_and_test_second:
    jobs:
      - build-second
      - test-second
